### ISSUE TITLE
Bump a major when changing rules

### ISSUE THREAD

**Issue by ross-** [uber/lint-trap#85]
New lint-trap versions may introduce rules that can break builds without warning. For example, a recent version of lint-trap added eslint.no-shadow, which broke things for me.

Let's be sure to bump a major when new rules are introduced.

**Comment by malandrew** [comment]
Cool deal. Next version will be 1.0.0. I might queue up a few rules at a time on a PR that will remain open until we decide to submit a new major release. If you have any other suggestions around this, let me know.

**Comment by malandrew** [comment]
Closing this. Will creating a 2.0.0 branch where new rules get merged into.
