### ISSUE TITLE
valid-jsdoc shouldn't require return for functions without returns

### ISSUE THREAD

**Issue by Willyham** [uber/lint-trap#86]
Having to add '@return {void}' for functions with no return value is both a pain and not obvious. Consider modifying the rule to ignore '@returns' when there is no return statement in the function:

https://github.com/eslint/eslint/blob/master/docs/rules/valid-jsdoc.md#requirereturn

**Comment by malandrew** [comment]
Will add this shortly

**Comment by malandrew** [comment]
Fixed by https://github.com/uber/lint-trap/pull/88
